### ISSUE TITLE
Weekly 3-5min pitch by one rep every week on Friday - Industry-focused

### ISSUE THREAD

**Issue by TFariq** [Tonomy-Foundation/Tonomy-ID-BD#113]
Acceptance Criteria:
1. Designate a representative to deliver the weekly pitch.
2. Prepare a concise and engaging 3-5 minute pitch on industry-specific topics.
3. Share the pitch with the targeted audience through the appropriate communication channels.
4. Collect feedback and inquiries generated by the pitch.
5. Track the impact of the pitch on lead generation and engagement.
6. Report the results of the weekly pitch to the team.

**Comment by shayansal** [comment]
Remove number 5-6 as this would be an internal pitch for training purposes.
