### ISSUE TITLE
Write all features down

### ISSUE THREAD

**Issue by TFariq** [Tonomy-Foundation/Tonomy-ID-BD#114]
_Acceptance_ Criteria:
1. Compile a comprehensive list of Tonomy ID features in one document
2. Analyze and categorize features based on their relevance to specific use cases.
3. Assign features to respective use cases within the team.
4. Ensure each use case is adequately covered with relevant features.

**Comment by BINLA123** [comment]
Tasks should be further broken down into 4 tasks

**Comment by shayansal** [comment]
1. First we need a document with all features listed down ideally on Miro - One Team Member
2. Research which feature aligns to what use case - Each Team Member do 1/4 of features
3. Add to Miro board
