### ISSUE TITLE
Set up payment

### ISSUE THREAD

**Issue by TFariq** [Tonomy-Foundation/Tonomy-ID-BD#119]
Acceptance Criteria:
1. Establish a secure and efficient payment system for Tonomy ID's services.
2. Ensure payment processing complies with industry standards and regulations.
3. Conduct thorough testing to verify payment system functionality.
4. Monitor payment processing for accuracy and security.

**Comment by shayansal** [comment]
@theblockstalk has an invoicing system set up. Just needs to test this.

**Comment by BINLA123** [comment]
Jack needs to test this

**Comment by theblockstalk** [comment]
this is done. see https://discord.com/channels/1029385699071381524/1039499044768202782/1153602512469905439
