### ISSUE TITLE
Pilot testing campaigns, start at 50 euros, A/B testing

### ISSUE THREAD

**Issue by TFariq** [Tonomy-Foundation/Tonomy-ID-BD#120]
Acceptance Criteria:
1. Initiate pilot advertising campaigns with a budget of 50 euros.
2. Set up A/B testing for campaign elements, such as ad creatives, targeting, and messaging.
3. Monitor campaign performance and collect data on key metrics.
4. Analyze A/B test results to identify the most effective campaign elements.
5. Make data-driven adjustments to optimize campaign performance.

**Comment by shayansal** [comment]
First campaign already started G Ads wwith 15 euros per day
