### ISSUE TITLE
Create a comprehensive list of Tonomy ID features in one document

### ISSUE THREAD

**Issue by BINLA123** [Tonomy-Foundation/Tonomy-ID-BD#122]
Acceptance Criteria;

1. Compile and create a One-Stop- comprehensive document for Tonomy ID features
2. List subfeatures
3. Call Jack and work with him on making doc complete
3. Make sure the document is available to the team

**Comment by theblockstalk** [comment]
https://www.canva.com/design/DAFnktNOWKU/Ps1zXw3XICaEMiB0R4Ghkg/view#17

**Comment by theblockstalk** [comment]
https://docs.google.com/document/d/1SAesKvWxpr7xAw2wjV5zAJYyZUA7oZLzNBGecwkiId0/edit#heading=h.wmmkj4pijwdw
