### ISSUE TITLE
 Make sure features are analyse and categorize based on their relevance to specific use cases.

### ISSUE THREAD

**Issue by BINLA123** [Tonomy-Foundation/Tonomy-ID-BD#123]
Acceptance Criteria;
  
- For each feature (e.g. SSO) and sub-feature (e.g. smart contract transaction is sub-feature of signatures):
- write out a list of different value propositions that feature delivers to businesses/orgs/goverment with
  - customer profile
  - pain point solved or business initiative
  - the business proposition (e.g. does it reduce risks, increase profits, ....)

Follow up
- discuss which of these makes sense to target, competitors, market etc...

**Comment by MD-SHAHRIAR-FAIM-RODDRO** [comment]
https://docs.google.com/document/d/16fLf_SpR9c-A8bPDHnxSipbk_TzT9DgJEPtV2Z8zNPE/edit?usp=sharing

**Comment by shayansal** [comment]
Please make it more concrete and less generated by AI. try to think of actual use cases for each feature. Most of the document is AI generated text that makes little sense + is not valuable to read for anyone
