### ISSUE TITLE
Comparing Google Tags vs. Vercel. vs Matomo in Google Ads for Tonomy ID

### ISSUE THREAD

**Issue by MD-SHAHRIAR-FAIM-RODDRO** [Tonomy-Foundation/Tonomy-ID-BD#159]
**Description:**
This task involves a thorough analysis and comparison of using Google Tags and Matomo for tracking and analytics in Google Ads for Tonomy ID. The goal is to evaluate which platform offers more effective tracking, analytics, and insights to optimize advertising campaigns.

**Outcome:**

Research and Evaluation: Begin by researching and understanding the capabilities of Google Tags and Matomo. Assess their features, data collection methods, and integration with Google Ads.

Setting Clear Objectives: Define clear objectives for tracking and analytics, such as measuring campaign performance, user behavior, and conversion tracking.

Implementation: Set up Google Tags and Matomo tracking on your website or landing pages. Ensure that both platforms are properly configured to capture relevant data.

Data Collection: Allow both platforms to collect data over a specific time frame, typically a few weeks to a month. Ensure that you collect data from the same advertising campaigns for an accurate comparison.

Performance Metrics: Track and compare key performance metrics, such as click-through rates (CTR), conversion rates, bounce rates, and the effectiveness of different ad creatives.

User Behavior Analysis: Analyze user behavior data, including page views, session durations, and exit pages, to understand how visitors interact with your website after clicking on an ad.

Conversion Tracking: Evaluate the accuracy of conversion tracking for both platforms. Determine if they are equally effective in attributing conversions to specific ad campaigns.

Data Accuracy and Consistency: Check for discrepancies or inconsistencies in the data collected by Google Tags and Matomo. Identify any discrepancies that may arise due to differences in tracking methodologies.

Cost Analysis: Consider the cost associated with using Google Tags and Matomo, factoring in subscription fees or any additional expenses.

Report Generation: Generate detailed reports for both platforms to compare their respective capabilities in providing insights and analytics.

Recommendations: Based on the results and insights gathered, provide recommendations on which tracking platform is more effective for Tonomy ID's Google Ads campaigns.

Documentation: Create a comprehensive report documenting the entire process, findings, and recommendations for future reference.

**Comment by theblockstalk** [comment]
Google Ads graph(clicks) last 8 days(Oct 15 - Oct 23)
Sunday (Oct 15) - 13 clicks/ Cost:€1.73
Monday (Oct 16) - 15 clicks Cost:€1.74
Tuesday (Oct 17) - 23 clicks Cost:€1.69
Wednesday (Oct 18) - 17 clicks Cost:€1.21
Thursday (Oct 19) - 7 clicks Cost:€1.10
October (Oct 20) - 9 clicks Cost:€1.10
Saturday (Oct 21) - 11 clicks Cost:€1.30
Sunday (Oct 22) - 4 clicks Cost:€0.58
Monday (Oct 23) - 0 clicks Cost:€0.00
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3hnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c1c0a624a5f51ee7f908e38e011cbde45a29da2/image.png)

Google Ads graph(Impressions) last 8 days(Oct 15 - Oct 23)
Sunday = 318 Impressions(Oct 15)
Monday = 216 Impressions(Oct 16)
Tuesday = 1032 Impressions(Oct 17)
Wednesday = 1099 Impressions(Oct 18)
Thursday = 113 Impressions(Oct 19)
October  = 218 Impressions(Oct 20)
Saturday = 399 Impressions(Oct 21)
Sunday =  69  Impressions(Oct 22)
Monday =  26  Impressions(Oct 23)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3B5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--135630cb80ee5c529d14b213539d24174cfc08eb/Screenshot_5.png)

Google Ads graph(Conversions) last 8 days(Oct 15 - Oct 23)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEZ5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ba1068f01867bb2e4e57c5dd11def4c90ed234a/Screenshot_6.png)
Google Ads Campaign performance last 8 days(Oct 15 - Oct 23)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGh5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--16778d71994febfddc5910c65bf758d01448025b/Screenshot_8.png)

**Comment by theblockstalk** [comment]
Matomo last 8 days
Sunday = 20 Visits (Oct 15)
Monday = 508 Visits (Oct 16)
Tuesday = 295 Visits (Oct 17)
Wednesday = 47 Visits (Oct 18)
Thursday = 44 Visits (Oct 19)
October  = 40 Visits (Oct 20)
Saturday = 32 Visits (Oct 21)
Sunday =  20 Visits (Oct 22)
Monday =  29  Visits (Oct 23)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzFnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--358b73597be7c1482b615e6f6c6adeb937b443ac/image.png)

Returning Visits Over Time
Sunday (Oct 15) - 1 Returning Visits
Monday (Oct 16) - 15 Returning Visits
Tuesday (Oct 17) - 12 Returning Visits
Wednesday (Oct 18) - 6 Returning Visits
Thursday (Oct 19) - 6 Returning Visits
October (Oct 20) - 8 Returning Visits
Saturday (Oct 21) - 6 Returning Visits
Sunday (Oct 22) - 5 Returning Visits
Monday (Oct 23) - 10 Returning Visits
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL04xQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--79420f0ddf648ed423b4689f206b057b4aa1d460/Screenshot_15.png)
