### ISSUE TITLE
LinkedIn Weekly Content Strategy: 4 Posts per Week for Tonomy ID (Sprint starting 17 October)

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-BD#167]
Create 2 Infographics per week
Send into Marketing Channel for Shayans approval

**Comment by MD-SHAHRIAR-FAIM-RODDRO** [comment]
https://www.canva.com/design/DAFzExpeFBs/KKg85cMlNNrJxaKeh-GrSA/edit?utm_content=DAFzExpeFBs&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
