### ISSUE TITLE
Research industry events (sprint starting 17 October)

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-BD#170]
Acceptance Criteria:
1. Identify industry events to attend within this year

Follow up
- discuss and decide to go to events

**Comment by MD-SHAHRIAR-FAIM-RODDRO** [comment]
https://docs.google.com/document/d/1J_SW8KaXfkn2NpjUnnZn-GkxZ7e90CvGw_ugGZMK8nw/edit
