### ISSUE TITLE
Optimizing Google Ads Campaign with a €50 Weekly Budget

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-BD#171]
Acceptance criteria

- [ ] create 3 different campeigns for separate industry pages
- [ ] use the Goal tracking to measure conversion for meeting booking
- [ ] check matomo and whitelist the geographic locations we want
- [ ] pause/cancel the current campaign - ensure we still get the €400 credit

**Comment by shayansal** [comment]
Scheduled Meeting with Google Rep
