### ISSUE TITLE
Prepare product requirements workshop for BD (sprint starting 14 Nov)

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-BD#174]
Acceptance criteria

- [ ] copy the latest "Product requirements workshop" board from https://miro.com/app/dashboard/
- [ ] prepare

**Comment by MD-SHAHRIAR-FAIM-RODDRO** [comment]
https://miro.com/welcomeonboard/cVlweVZpZnpZSGViYzBXYXVOMzRlRzFCSlRiZ3hhY001MWY5ZVFMejFPUVlEa2RMRG53dVcxWXNaTW94OUJtenwzNDU4NzY0NTU4NzIwMjU3OTcwfDI=?share_link_id=705833777978
