### ISSUE TITLE
L1 competitor analysis

### ISSUE THREAD

**Issue by shayansal** [Tonomy-Foundation/Tonomy-ID-BD#181]
- Wallet system comparison
- Identity Layer comparison
- Signature process
- TPS / Scalability
- Security
- Governance
- DAO factory
- Decentralization
- Simplicity & user friendliness
- 
Integrate into deck

**Comment by theblockstalk** [comment]
- block time/latency

**Comment by theblockstalk** [comment]
https://twitter.com/scalinglabs/status/1635895854010880002
https://twitter.com/dfinity/status/1514320424380755968/photo/1

- transaction costs
