### ISSUE TITLE
Create videos for LinkedIn

### ISSUE THREAD

**Issue by shayansal** [Tonomy-Foundation/Tonomy-ID-BD#190]
Create 4 videos showcasing Tonomy ID to be posted on Linkedin

**Comment by MD-SHAHRIAR-FAIM-RODDRO** [comment]
https://www.canva.com/design/DAFzdjv6q0s/a0e96tgyNPfvyOHtuOrXcw/edit?utm_content=DAFzdjv6q0s&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
