### ISSUE TITLE
Prepare the BD team sprint review presentation (Sprint starting 14 Nov)

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-BD#201]
Acceptance criteria

- [ ] Outline the complete BD activities on our sales/marketing channels
- [ ] For each channel, provid an overview of our current follows/viewers and any insights from the month
- [ ] Provide an overview of our current leads/clients and next steps with each

**Comment by MD-SHAHRIAR-FAIM-RODDRO** [comment]
https://docs.google.com/presentation/d/10uQ9qKr8Jtj79JmdbwUam4AwnhbEhfqTmpFgHaTYMOo/edit?usp=sharing
