### ISSUE TITLE
Research and choose a Webflow template for tonomy.foundation website

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-BD#205]
Acceptance criteria

- [ ] Resarch and choose a webflow template that has similar structures and components as the tonomy.foundation website

It should be visually aesthetic and have flexible components so that we can easily migrate the current website, and also build new pages in the future

https://webflow.com/templates

**Comment by MD-SHAHRIAR-FAIM-RODDRO** [comment]
https://docs.google.com/document/d/1wsigx5Vt0f0jMo-skgJiLcMfZtNh0wTFqGSTjLb8EP0/edit?usp=sharing
