### ISSUE TITLE
Define Twitter & Marketing Strategy 

### ISSUE THREAD

**Issue by shayansal** [Tonomy-Foundation/Tonomy-ID-BD#226]
- Analyze different channels like twitter
- Identify communities and groups to target
- Identify key influencers
- Create a communication strategy that each Tonomy team member can execute on their account
- Create same strategy for Pangea 
- Figure out LinkedIn

**Comment by theblockstalk** [comment]
from Shayan https://docs.google.com/document/d/1o0DpmStIhYFnV4FrWpAVUpJiBbbau2EZNLZnkbnadaU/edit
