### ISSUE TITLE
Investor Pitch Deck - short (cold outreach)

### ISSUE THREAD

**Issue by shayansal** [Tonomy-Foundation/Tonomy-ID-BD#229]
Extensive deck for investor presentation 
pangea strategy: https://docs.google.com/document/d/1qCHvBiHFZJDE1N_R_dO59f_Rznbg7lRkPooAb8hWcyE/edit
tonomy white paper: https://docs.google.com/document/d/1CBObS9XX6Q68Fy54QjK9oZWTdNfqNFS-cTHxCvY3kkQ/edit
story - outline: https://docs.google.com/document/d/1wuLKghFEDhNWo9C-eVLeqoZA--z67y9m7lbrJfP-8NE/edit#heading=h.mcxh3kxzckro

**Comment by theblockstalk** [comment]
https://www.canva.com/design/DAF37XytDZ0/XQI0G21-FcexERZ8BxMfSQ/edit

**Comment by theblockstalk** [comment]
- create a story
- couple of rounds of iterations
- visual upgrades and consistent

**Comment by theblockstalk** [comment]
story:
- pangea virtual nation story
- global citizenship
- also need to show value propositions for businesses
- tech powering it from the surface level

more technical details. get a deeper understanding
- website
- white papers etc...
