### ISSUE TITLE
Create list of VCs

### ISSUE THREAD

**Issue by shayansal** [Tonomy-Foundation/Tonomy-ID-BD#242]
**Accounts to research:**

- Early Stage Crypto VCs
- Early Stage GovTech, Smart Cities, Social Impact, VCs
- Early stage VCs
- Family Offices
- Angel Investors
- Prioritise crypto related VCs
- 
**Output:** 

1. Create a google sheet of 500 to 1000 VCs websites and ideally a short description
2. Find people to contact at the VCs through Seamless.ai and LinkedIn
3. Check with Shayan for progress updates and help

**Comment by MD-SHAHRIAR-FAIM-RODDRO** [comment]
https://docs.google.com/spreadsheets/d/1hoskCFY5kLqGihHS-NtzjXeg8OC52gV1f-kidOZuFTc/edit?usp=sharing
