### ISSUE TITLE
Create Site v1 for Pangea

### ISSUE THREAD

**Issue by shayansal** [Tonomy-Foundation/Tonomy-ID-BD#243]
1. wireframes
2. mid fidelity
3. website
4. reactivity
5. publish
6. SEO optimizations

**Comment by theblockstalk** [comment]
TODO website checks for before friday launch
- all links working
- no english mistakes
- copy makes sense
- images finished (imported images need copywright permission)
- logo, name, favicon
- site metadata for page view previews
- responsive
- colour consistency
- privacy policy and cookie consent
- header menu hide unfinished pages
- site under construction notice??
