### ISSUE TITLE
Find help for investments

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-BD#277]
Create some job listings for chief commercial officer/CIO at Tonomy Foundation

Acceptance criteria:

- [ ] create a document explaining the role responsibilities and remuneration
- [ ] about working with Tonomy Foundation, about Pangea project.
- [ ] publish this on LinkedIn
- [ ] have a challenge to vet them with

Ideal candidate:
- existing network of investors
- skills in marketing
- skills in sales
- experience with pitch decks, valuations, business plans
- experience with crypto investing ICO/IEO/IDO
- experience with exchange listing
- technology native, Experience in web3 sector. identity, government, DAOs, defi

Follow up:
- chat with prospective, filter
- final chat with filtered candidates

**Comment by chetanabhardwaj** [comment]
Here is the JD. Kindly review it
https://docs.google.com/document/d/1qu1Mv5rTtd6sAIJwEMATRGR3RdwSO0dv_kiuW1GN7t0/edit
https://docs.google.com/document/d/1E42yYTOe9GpqTK5AX8OTIcgc5zoaMFiHH1W7g9IK3vo/edit

**Comment by theblockstalk** [comment]
postponed till investor advice
