### ISSUE TITLE
Website team credibility

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-BD#281]
Acceptance criteria

- For each team member, review linkedin/other career documents
- check what role the team member holds, if they are a co-founder, advisor or board member
- Formulate a maximum 250 character description of their most credibility providing institutions they have worked for and studied at, and how long they have worked in a field related to their role with Tonomy Foundation
- check with the team member it is correct and if there is anything else that could/should be added

Old text:
```
Jack Tanner - CTO
Our tech-savvy CTO and Co-Founder, Jack, is not only passionate about SSI development and a fan of techno music, but he's also an innovator at heart. With a deep expertise in all things tech, Jack is a valuable asset to our team, and we're thrilled to have his innovative spirit driving our project
```

New text:
```
Jack Tanner - CTO, Co-Founder & Board
Masters of Computer Science from Imperial College London and BEng from University of Queensland. 8 years experience as blockchain engineer including working with Atos and MN in finTech, social, govTech and other sectors. Taught blockchain in London with Ethereum Foundation members in early 2016, and major contributor to Ethereum upgradeability standards. Self-Sovereign identity engineer for 4 years with major contributions to DIF and W3C standards. Pioneered 3 startups.
```

**Comment by MD-SHAHRIAR-FAIM-RODDRO** [comment]
https://docs.google.com/document/d/167zoNBm4IsxQU377gpmYL4ccPhFEDTR35_Ou7A-6qWI/edit?usp=sharing

**Comment by theblockstalk** [comment]
should also do this for Rheet Ouder ... (ambassador) https://www.linkedin.com/in/rhettoudkerkpool/
also ask Amit to create an image file for him
