### ISSUE TITLE
Research IDO/IEO or launchpad platforms

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-BD#296]
Acceptance criteria:

- [ ] Research and document options for running an IDO/IEO/ICO through a platform
- [ ] document the feels, onboarding path, flows and how we can customize, weather we can add KYC and token sale contract, and compliance requirements for users

See roadmap plan https://discord.com/channels/1029385699071381524/1161673628144906271/1260566797099339796

What we need to know:
- Reputation
- Pros/cons
- Costs
- Outcomes
- What is their audience and success rate
- Other important information that seems relevant

**Comment by priyanka-kasture** [comment]
progressing well
jack has reached out to all contacts
Michael introduced us to GSR
