### ISSUE TITLE
Plan Digital Identity Week

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-BD#314]
https://www.google.com/url?q=https://www.terrapinn.com/exhibition/identity-week/index.stm&sa=D&source=calendar&ust=1715415938701009&usg=AOvVaw05mrfpASYup_0KDWcuQIcX

on the 11-12 of Juni, this year
we have a stand
and 10 passes
for the identity week amsterdam
Now, hans van mechelen (from belgium) is also coming, I want to make sure we use all the passes and that we have a proper stand
Can I forward you the emails and that you coordinate with the event maker?
Also Jack has a speaking slot

Acceptance criteria:

- [ ] plan and execution for what we need for identity week: stand, flyers, speaking topic etc...

**Comment by chetanabhardwaj** [comment]
https://docs.google.com/document/d/12KSsA1HwTTqIvy0qjpsGnj_QZN4Z0H4wwF2wwuuRvgw/edit?usp=sharing
