### ISSUE TITLE
Budget planning

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-BD#315]
Acceptance criteria

- [ ] Updated balance sheet, cashflow and runway
- [ ] Calculate budget for marketing person (Willo) and Trezna

**Comment by chetanabhardwaj** [comment]
https://docs.google.com/spreadsheets/d/1KjYrJ_vjSkJuhqlWTQ_EV98qszQD2zAkOMJa44tTHy8/edit#gid=0
