### ISSUE TITLE
Risk assessment in the pangea project 

### ISSUE THREAD

**Issue by chetanabhardwaj** [Tonomy-Foundation/Tonomy-ID-BD#318]
Acceptance Criteria:
1. Write down all possible risk associate with the project
2. How to mitigate the risk

**Comment by theblockstalk** [comment]
checkout our legally compliant whitepaper: https://github.com/Tonomy-Foundation/documentation/blob/c004725692f3afbbff5d0f37aa83236f20b4825b/whitepapers/Pangea%20and%20LEOS%20Official%20Whitepaper%20-%20EU%20Compliant%20v1.0.1.pdf?raw=true
