### ISSUE TITLE
List of cryptocurrency contain creator in YouTube 

### ISSUE THREAD

**Issue by chetanabhardwaj** [Tonomy-Foundation/Tonomy-ID-BD#322]
Acceptance Criteria:
Make a list to cryptocurrency contain creator in Europe. Youtuber/ Tweeter/ Instragram
List there country name, email ID and number of  followers , contact information. 
Countries you can focus : Norway, Belgium. Austria, Switzerland Spain, Germany, Luxembourg etc

**Comment by MD-SHAHRIAR-FAIM-RODDRO** [comment]
https://docs.google.com/spreadsheets/d/1WY85Z7WNK0JbswoIZ6kaTHPNtlJtnBgzoc5juCXdknE/edit#gid=0
