### ISSUE TITLE
Research and engage marketing agency

### ISSUE THREAD

**Issue by chetanabhardwaj** [Tonomy-Foundation/Tonomy-ID-BD#326]
Acceptance Criteria:
1. Look for W3 marketing agencies and Set up a call.

**Comment by theblockstalk** [comment]
https://www.growthchain.io/blog/best-web3-marketing-agencies

**Comment by theblockstalk** [comment]
I have setup calls with
- lunarstrategy.com
- ninjapromo.io
- justevolve.io (met in London)

And reached out to 
- https://www.singlegrain.com/
