### ISSUE TITLE
Townhall Promotion and Preps

### ISSUE THREAD

**Issue by priyanka-kasture** [Tonomy-Foundation/Tonomy-ID-BD#361]

**Comment by priyanka-kasture** [comment]
Presentation: https://www.canva.com/design/DAGQcvk3hi8/AsEYI98uUh6ljOo-LnotAg/edit?utm_content=DAGQcvk3hi8&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

Doc with details: https://docs.google.com/document/d/1nuGm-4zSeJtM0LaBeG-qqLWynxhSBopqhFAlfHcJkO8/edit?usp=sharing

**Comment by theblockstalk** [comment]
Just made some changes to the two slides I will present. Removed a lot of text.
