### ISSUE TITLE
Zealy Quest 3rd Sprint

### ISSUE THREAD

**Issue by priyanka-kasture** [Tonomy-Foundation/Tonomy-ID-BD#365]

**Comment by priyanka-kasture** [comment]
Details: https://docs.google.com/document/d/1YRgm--GwbN8yYpbNMbkdtZ39tm6yFqDUoPtv9GoKMpc/edit?usp=sharing

**Comment by willspatrick** [comment]
Zealy Sprint 3 report - https://docs.google.com/document/d/1rWKxgV3hFlTsR3GLMnKCTebuz-Ij_Gohh9icRRALZJI/edit?usp=sharing
