### ISSUE TITLE
Antelope Blockchain Page + Figure out a strategy approaching Telos and perhaps other Antelope chains

### ISSUE THREAD

**Issue by BINLA123** [Tonomy-Foundation/Tonomy-ID-BD#99]
Acceptance Criteria;
  
1. Identify and present the best Antelope Blockchain pages
2.  Paint down a strategy on how to engage them

**Comment by theblockstalk** [comment]
the first is done https://tonomy.io/antelope-wallet-telos-eos-wax/

The second I suggest be made into a separate task. It is quite separate to the first task, and quite some work.
